# Generated by Django 6.0.6 on 2026-06-23 08:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('goal_type', models.CharField(choices=[('daily', '24 Hours / Daily'), ('weekly', '7 Days'), ('monthly', '1 Month'), ('six_month', '6 Months'), ('yearly', '1 Year')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_minutes_per_day', models.PositiveIntegerField(default=15, help_text='Keep it small so daily work feels easy.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tracker.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('daily_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_progress', to='tracker.dailyentry')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='tracker.goal')),
            ],
            options={
                'ordering': ['goal__category__name', 'goal__title'],
                'unique_together': {('daily_entry', 'goal')},
            },
        ),
        migrations.CreateModel(
            name='PrayerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer', models.CharField(choices=[('fajr', 'Fajr'), ('dhuhr', 'Dhuhr'), ('asr', 'Asr'), ('maghrib', 'Maghrib'), ('isha', 'Isha')], max_length=20)),
                ('status', models.CharField(choices=[('jamaat', 'Jamaat'), ('single', 'Single'), ('missed', 'Missed')], default='missed', max_length=20)),
                ('sunnah_done', models.BooleanField(default=False)),
                ('daily_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to='tracker.dailyentry')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('daily_entry', 'prayer')},
            },
        ),
    ]
